name = "kebab-case"
main = "src/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
workers_dev = true

[assets]
directory = "./public"
binding = "ASSETS"
not_found_handling = "404-page"

[[d1_databases]]
binding = "DB"
database_name = "kebab-case-db"
database_id = "0102a9f0-75f5-4ee5-8cf6-a8f0f875fd6a"
